[package]
name = "CoinDeployer"
version = "1.0.1"
authors = []

[addresses]
yuzu_framework = "0xfab1d67f58e405701128ab5155ddcc7fabae8fdd2eba9afa93eda9864f34b872"
[dev-addresses]

[dependencies.AptosFramework]
git = "https://github.com/aptos-labs/aptos-core.git"
rev = "main"
subdir = "aptos-move/framework/aptos-framework"

[dev-dependencies]
