[package]
name = "CoinDeployer"
version = "1.0.1"
authors = []

[addresses]
yuzu_framework = "d66d7422ebdd68dc4299d2601793aa9b3db6a047ffdeb6f03d132b3fea52cc96"
[dev-addresses]

[dependencies.AptosFramework]
git = "https://github.com/aptos-labs/aptos-core.git"
rev = "main"
subdir = "aptos-move/framework/aptos-framework"

[dev-dependencies]
